#!/usr/bin/env bash
# Expands the three canonical values from devcontainer.env (HTTP_PROXY, NO_PROXY,
# JAVA_TOOL_OPTIONS — injected via runArgs --env-file, which cannot expand variables)
# into the full proxy setup. Run at postCreate; idempotent.
#
#   ~/.proxy.env       HTTPS_PROXY + lowercase variants — sourced by ~/.bashrc for
#                      interactive shells and by postCreateCommand for the cache warm-up
#   ~/.m2/settings.xml Maven <proxies> — Maven's artifact resolution ignores proxy
#                      env vars AND java system props; settings.xml is the only way
#
# With HTTP_PROXY empty (the default): ~/.proxy.env is emptied and a previously
# generated settings.xml is removed → the container runs proxy-less.
set -euo pipefail

PROXY_ENV="$HOME/.proxy.env"
M2_SETTINGS="$HOME/.m2/settings.xml"
GENERATED_MARK="GENERATED by .devcontainer/setup-proxy.sh"

# Hook ~/.proxy.env into interactive shells (idempotent).
touch "$HOME/.bashrc"
grep -qF '.proxy.env' "$HOME/.bashrc" \
  || printf '\n[ -f "$HOME/.proxy.env" ] && . "$HOME/.proxy.env"\n' >> "$HOME/.bashrc"

if [ -z "${HTTP_PROXY:-}" ]; then
  : > "$PROXY_ENV"
  if [ -f "$M2_SETTINGS" ] && grep -qF "$GENERATED_MARK" "$M2_SETTINGS"; then
    rm -f "$M2_SETTINGS"
  fi
  echo "[setup-proxy] HTTP_PROXY empty — proxy-less setup, no $M2_SETTINGS"
  exit 0
fi

NO_PROXY="${NO_PROXY:-localhost,127.0.0.1}"

cat > "$PROXY_ENV" <<EOF
# $GENERATED_MARK from devcontainer.env — do not edit.
export HTTPS_PROXY="$HTTP_PROXY"
export http_proxy="$HTTP_PROXY"
export https_proxy="$HTTP_PROXY"
export no_proxy="$NO_PROXY"
EOF

# http://host:port → host, port
hostport="${HTTP_PROXY#*://}"
hostport="${hostport%%/*}"
host="${hostport%%:*}"
port="${hostport##*:}"

# NO_PROXY (comma-separated, leading-dot suffixes) → java nonProxyHosts
# ('|'-separated, '*.' wildcards)
nph=",${NO_PROXY}"
nph="${nph//,./,*.}"
nph="${nph#,}"
nph="${nph//,/|}"

mkdir -p "$(dirname "$M2_SETTINGS")"
cat > "$M2_SETTINGS" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- $GENERATED_MARK from devcontainer.env — do not edit. -->
<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
  <proxies>
    <proxy>
      <id>env-http</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>${host}</host>
      <port>${port}</port>
      <nonProxyHosts>${nph}</nonProxyHosts>
    </proxy>
    <proxy>
      <id>env-https</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>${host}</host>
      <port>${port}</port>
      <nonProxyHosts>${nph}</nonProxyHosts>
    </proxy>
  </proxies>
</settings>
EOF
echo "[setup-proxy] wrote $PROXY_ENV and $M2_SETTINGS (proxy ${host}:${port}, nonProxyHosts ${nph})"
