databaseChangeLog:
  - changeSet:
      id: "003-create-location-schema"
      author: "Mark Iarovih"
      logicalFilePath: "003-create-location-schema.yml"
      objectQuotingStrategy: "QUOTE_ONLY_RESERVED_WORDS"
      preConditions:
        - onFail: MARK_RAN
        - onFailMessage: "Database table [portal_location] already initialized"
        - not:
            - tableExists:
                tableName: "portal_location"
      changes:
        - createTable:
            tableName: "portal_location"
            columns:
              - column:
                  name: "id"
                  type: "BIGINT"
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: "version"
                  type: "NUMBER(38, 0)"
                  defaultValueNumeric: "1"
                  constraints:
                    nullable: false
              - column:
                  name: "name"
                  type: "VARCHAR(255)"
                  constraints:
                    nullable: false
              - column:
                  name: "federal_state"
                  type: "VARCHAR(255)"
                  constraints:
                    nullable: false
        - loadData:
            tableName: "portal_location"
            file: classpath:db/data/location-data-init.csv
            separator: ;
            columns:
              - column:
                  name: "name"
                  header: "name"
              - column:
                  name: "federal_state"
                  header: "federal_state"
