databaseChangeLog:
  - changeSet:
      id: "016-create-mailbox-message-schema"
      author: "Mark Iarovih"
      logicalFilePath: "016-create-mailbox-message-schema.yml"
      objectQuotingStrategy: "QUOTE_ONLY_RESERVED_WORDS"
      preConditions:
        - onFail: MARK_RAN
        - onFailMessage: "Database tables [portal_notification] already initialized"
        - not:
            - tableExists:
                tableName: "portal_mailbox_log"
      changes:
        - createTable:
            tableName: "portal_mailbox_log"
            columns:
              - column:
                  name: "id"
                  type: "BIGINT"
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: "version"
                  type: "NUMBER(38, 0)"
                  defaultValueNumeric: "1"
                  constraints:
                    nullable: false
              - column:
                  name: "subject"
                  type: "VARCHAR(255)"
                  constraints:
                    nullable: false
              - column:
                  name: "text"
                  type: "VARCHAR(255)"
                  constraints:
                    nullable: false
              - column:
                  name: "status"
                  type: "VARCHAR(255)"
                  constraints:
                    nullable: false
              - column:
                  name: "send_at"
                  type: "timestamptz"
                  defaultValueComputed: "NOW()"
                  constraints:
                    nullable: false
              - column:
                  name: "sender"
                  type: "VARCHAR(255)"
                  constraints:
                    nullable: false
              - column:
                  name: "receiver"
                  type: "VARCHAR(255)"
                  constraints:
                    nullable: false
              - column:
                  name: "profile_id"
                  type: "BIGINT"
                  constraints:
                    nullable: false
              - column:
                  name: "service_id"
                  type: "BIGINT"
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            constraintName: "fk_mailbox_log_profile"
            baseTableName: "portal_mailbox_log"
            baseColumnNames: "profile_id"
            referencedTableName: "portal_profile"
            referencedColumnNames: "id"
            onDelete: CASCADE
        - addForeignKeyConstraint:
            constraintName: "fk_mailbox_log_service"
            baseTableName: "portal_mailbox_log"
            baseColumnNames: "service_id"
            referencedTableName: "portal_service"
            referencedColumnNames: "id"
            onDelete: CASCADE
        - loadData:
            file: classpath:db/data/mailbox-message-data-init.csv
            tableName: "portal_mailbox_log"
            separator: ";"
