databaseChangeLog:
  - include:
      file: classpath:db/changelog/000-create-profile-schema.yml
  - include:
      file: classpath:db/changelog/001-create-relationship-schema.yml
  - include:
      file: classpath:db/changelog/002-create-user-schema.yml
  - include:
      file: classpath:db/changelog/003-create-location-schema.yml
  - include:
      file: classpath:db/changelog/004-update-profile-schema.yml
  - include:
      file: classpath:db/changelog/005-create-document-schema.yml
  - include:
      file: classpath:db/changelog/006-update-profile-payment-data.yml
  - include:
      file: classpath:db/changelog/007-create-domain-and-category-schemas.yml
  - include:
      file: classpath:db/changelog/008-create-service-schema.yml
  - include:
      file: classpath:db/changelog/009-create-admin-user-schema.yml
  - include:
      file: classpath:db/changelog/010-create-application-schema.yml
  - include:
      file: classpath:db/changelog/011-create-comment-schema.yml
  - include:
      file: classpath:db/changelog/012-create-dog-schema.yml
  - include:
      file: classpath:db/changelog/013-create-dog-application-schema.yml
  - include:
      file: classpath:db/changelog/014-create-consent-schema.yml
  - include:
      file: classpath:db/changelog/015-create-notification-schema.yml
  - include:
      file: classpath:db/changelog/016-create-mailbox-message-schema.yml
  - include:
      file: classpath:db/changelog/017-change-mailbox-message-schema.yml
  - include:
      file: classpath:db/changelog/018-update-consent-buergerportal.yml
  - include:
      file: classpath:db/changelog/019-update-profile-me-endpoint.yml
