spring:

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}?autoReconnect=true&targetServerType=master
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/keycloak/realms/portal
          jwk-set-uri: http://localhost:8888/keycloak/realms/portal/protocol/openid-connect/certs
